### ISSUE TITLE
glycanbuilder throwing ConcurrentModificationException - not multithreadable?

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#36]
```

java_1       | 2016-05-26 05:57:19 ERROR [dispatcherServlet]:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java_1       | java.util.ConcurrentModificationException
java_1       |  at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
java_1       |  at java.util.Vector$Itr.next(Vector.java:1137)
java_1       |  at org.eurocarbdb.application.glycanbuilder.LinkageStyleDictionary.getStyle(LinkageStyleDictionary.java:124)
java_1       |  at org.eurocarbdb.application.glycanbuilder.LinkageStyleDictionary.getStyle(LinkageStyleDictionary.java:111)
java_1       |  at org.eurocarbdb.application.glycanbuilder.LinkageRendererAWT.paintInfo(LinkageRendererAWT.java:76)
java_1       |  at org.eurocarbdb.application.glycanbuilder.AbstractGlycanRenderer.paintResidue(AbstractGlycanRenderer.java:321)
java_1       |  at org.eurocarbdb.application.glycanbuilder.AbstractGlycanRenderer.paintResidue(AbstractGlycanRenderer.java:310)
java_1       |  at org.eurocarbdb.application.glycanbuilder.GlycanRendererAWT.paint(GlycanRendererAWT.java:95)
java_1       |  at org.eurocarbdb.application.glycanbuilder.AbstractGlycanRenderer.paint(AbstractGlycanRenderer.java:206)
java_1       |  at org.eurocarbdb.application.glycanbuilder.GlycanRendererAWT.getImage(GlycanRendererAWT.java:256)
java_1       |  at org.eurocarbdb.application.glycanbuilder.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1839)
java_1       |  at org.eurocarbdb.application.glycanbuilder.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1820)
java_1       |  at org.glyspace.registry.utils.ImageGenerator.getImage(ImageGenerator.java:73)
java_1       |  at org.glytoucan.ws.controller.GlycanController.getGlycanImage(GlycanController.java:1018)
java_1       |  at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
java_1       |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java_1       |  at java.lang.reflect.Method.invoke(Method.java:497)
java_1       |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
java_1       |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
java_1       |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
java_1       |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
java_1       |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
java_1       |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
java_1       |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
java_1       |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
java_1       |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
java_1       |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
java_1       |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
java_1       |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
java_1       |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:237)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:112)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207)
java_1       |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
java_1       |  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
java_1       |  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
java_1       |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
java_1       |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
java_1       |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
java_1       |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
java_1       |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
java_1       |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
java_1       |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
java_1       |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
java_1       |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
java_1       |  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
java_1       |  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
java_1       |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
java_1       |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
java_1       |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java_1       |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java_1       |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java_1       |  at java.lang.Thread.run(Thread.java:745)

```

**Comment by aokinobu** [comment]
resolved in 1.2.6-TOCO simple change to just use iterator.

[commit log here](https://bitbucket.org/glycosw/wurcsglycanbuilder/commits/4c969f5f9025d4100bf6c775d3fdf963c3ffcf3f?at=master#chg-GlycanBuilder_WURCSextend/src/main/java/org/eurocarbdb/application/glycanbuilder/dataset/ResiduePlacementDictionary.java)

**Comment by aokinobu** [comment]
2016-11-25 08:09:46.042 ERROR 1 --- [-nio-80-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 08:09:46.047 DEBUG 1 --- [-nio-80-exec-10] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 08:09:46 UTC 2016, status=500, error=Internal Server Error, exception=java.util.ConcurrentModificationException, message=No message available, path=/glycans/G99827QE/image}
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
java.util.ConcurrentModificationException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
Can't expand repeating unit with unknown repeat count.
Can't expand repeating unit with unknown repeat count.
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.util.ConcurrentModificationException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:15:19.157 ERROR 1 --- [p-nio-80-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:15:19.158 ERROR 1 --- [p-nio-80-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:15:19.159 DEBUG 1 --- [p-nio-80-exec-7] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:15:19 UTC 2016, status=500, error=Internal Server Error, exception=java.lang.NullPointerException, message=No message available, path=/glycans/G81621YJ/image}
2016-11-25 09:15:19.160 DEBUG 1 --- [p-nio-80-exec-3] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:15:19 UTC 2016, status=500, error=Internal Server Error, exception=java.lang.NullPointerException, message=No message available, path=/glycans/G45036XE/image}
java.util.ConcurrentModificationException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:15:20.152 ERROR 1 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:15:20.154 DEBUG 1 --- [p-nio-80-exec-1] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:15:20 UTC 2016, status=500, error=Internal Server Error, exception=java.lang.NullPointerException, message=No message available, path=/glycans/G62442OW/image}
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.util.ConcurrentModificationException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.Exception: Invalid string format: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.util.ConcurrentModificationException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:25:49.112 ERROR 1 --- [-nio-80-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:25:49.132 DEBUG 1 --- [-nio-80-exec-10] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:25:49 UTC 2016, status=500, error=Internal Server Error, exception=java.util.ConcurrentModificationException, message=No message available, path=/glycans/G00036MO/image}
Warning: Could not get charToByteConverterClass!
2016-11-25 09:26:52.360 ERROR 1 --- [p-nio-80-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:26:52.368 DEBUG 1 --- [p-nio-80-exec-3] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:26:52 UTC 2016, status=500, error=Internal Server Error, exception=java.util.ConcurrentModificationException, message=No message available, path=/glycans/G00065MO/image}
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:26:52.730 ERROR 1 --- [p-nio-80-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:26:52.736 DEBUG 1 --- [p-nio-80-exec-5] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:26:52 UTC 2016, status=500, error=Internal Server Error, exception=java.util.ConcurrentModificationException, message=No message available, path=/glycans/G00071MO/image}
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
java.lang.NullPointerException
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:58:44.541 ERROR 1 --- [p-nio-80-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:58:44.547 DEBUG 1 --- [p-nio-80-exec-8] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:58:44 UTC 2016, status=500, error=Internal Server Error, exception=java.lang.NullPointerException, message=No message available, path=/glycans/G85673TR/image}
2016-11-25 09:58:45.234 ERROR 1 --- [p-nio-80-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
2016-11-25 09:58:45.255 DEBUG 1 --- [p-nio-80-exec-5] o.g.api.controller.RestErrorController   : errors:>{timestamp=Fri Nov 25 09:58:45 UTC 2016, status=500, error=Internal Server Error, exception=java.util.ConcurrentModificationException, message=No message available, path=/glycans/G17779FT/image}

**Comment by aokinobu** [comment]
2016-11-28 05:18:34.972 DEBUG 1 --- [-nio-80-exec-10] o.g.r.dao.SparqlDAOVirtSesameImpl        : query:> PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>
PREFIX glytoucan:  <http://www.glytoucan.org/glyco/owl/glytoucan#> SELECT DISTINCT ?SaccharideURI
?PrimaryId
 ?Sequence 
 FROM <http://rdf.glytoucan.org/sequence/wurcs>
FROM <http://rdf.glytoucan.org/core> WHERE {
?SaccharideURI a glycan:saccharide .
?SaccharideURI glytoucan:has_primary_id ?PrimaryId .
?SaccharideURI glytoucan:has_primary_id "G81621YJ" .
?SaccharideURI glycan:has_glycosequence ?GlycanSequenceURI .
?GlycanSequenceURI glycan:has_sequence ?Sequence .
?GlycanSequenceURI glycan:in_carbohydrate_format glycan:carbohydrate_format_wurcs .
}    

2016-11-28 05:18:34 ERROR LogUtils:152 - Error in GlycanBuilder
java.lang.NullPointerException
	at org.eurocarbdb.application.glycanbuilder.BookingManager.isAvailable(BookingManager.java:138)
	at org.eurocarbdb.application.glycanbuilder.BookingManager.isAvailable(BookingManager.java:130)
	at org.eurocarbdb.application.glycanbuilder.BookingManager.add(BookingManager.java:78)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:551)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:569)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:569)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:569)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:445)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:392)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:368)
	at org.eurocarbdb.application.glycanbuilder.renderutil.GlycanRendererAWT.getImage(GlycanRendererAWT.java:240)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1861)
	at org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1842)
	at org.glycoinfo.vision.generator.ImageGenerator.getImage(ImageGenerator.java:86)
	at org.glytoucan.api.controller.GlycanController.getGlycanImage(GlycanController.java:374)

**Comment by aokinobu** [comment]
a [new image generation architecture](http://code.glytoucan.org/system/images/) needs to be created for better handling issues such as this.
