### ISSUE TITLE
image generation: current image generation method cannot handle multi-threaded environments

### ISSUE THREAD

**Issue by aokinobu** [glytoucan/glytoucan.github.io#91]
o.g.api.controller.GlycanController      : image for G00015MO sequence:>WURCS=2.0/4,4,3/[u2122h][a1122h-1b_1-5][a1122h-1a_1-5][a2122h-1b_1-5_2*NCC/3=O]/1-2-3-4/a4-b1_b3-c1_c2-d1<
LogUtils:152 - Error in GlycanBuilder
java.lang.NullPointerException
at org.eurocarbdb.application.glycanbuilder.BookingManager.isAvailable(BookingManager.java:138)
at org.eurocarbdb.application.glycanbuilder.BookingManager.isAvailable(BookingManager.java:130)
 org.eurocarbdb.application.glycanbuilder.BookingManager.add(BookingManager.java:78)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:551)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:445)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:392)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:368)
 org.eurocarbdb.application.glycanbuilder.renderutil.GlycanRendererAWT.getImage(GlycanRendererAWT.java:240)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1861)
 org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1842)
 org.glycoinfo.vision.generator.ImageGenerator.getImage(ImageGenerator.java:86)

**Comment by aokinobu** [comment]
o.g.api.controller.GlycanController      : image for G00014MO sequence:>WURCS=2.0/4,4,3/[u2122h][a1122h-1b_1-5][a2122h-1b_1-5_2*NCC/3=O][a2112h-1b_1-5_2*NCC/3=O]/1-2-3-4/a4-b1_b3-c1_c4-d1<
LogUtils:152 - Error in GlycanBuilder
java.lang.Exception: Cannot place residue GalNAc in position(s) null
org.eurocarbdb.application.glycanbuilder.BookingManager.add(BookingManager.java:79)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.assignPosition(AbstractGlycanRenderer.java:551)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:445)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:392)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.computeBoundingBoxes(AbstractGlycanRenderer.java:368)
org.eurocarbdb.application.glycanbuilder.renderutil.GlycanRendererAWT.getImage(GlycanRendererAWT.java:240)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1861)
org.eurocarbdb.application.glycanbuilder.renderutil.AbstractGlycanRenderer.getImage(AbstractGlycanRenderer.java:1842)

**Comment by aokinobu** [comment]
[multi-threading issue](https://github.com/glytoucan/glytoucan.github.io/issues/36) because this is inconsistent.
